# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U9_9tfTw3F2XuqFn27emH7UG2Cpt4hKR
"""

from transformers import pipeline
import gradio as gr

# Load pre-trained sentiment analysis model
classifier = pipeline("sentiment-analysis")

def analyze_sentiment(text):
  """Analyzes the sentiment of the given text using the pre-trained model."""
  result = classifier(text)[0]
  label = result['label']
  score = result['score']
  return f"Sentiment: {label}, Score: {score:.4f}"


iface = gr.Interface(
    fn=analyze_sentiment,
    inputs=gr.Textbox(lines=5, placeholder="Enter text here..."),
    outputs="text",
    title="Sentiment Analysis",
    description="Analyze the sentiment of your text.",
)


iface.launch()

!pip install transformers gradio